export {default as ChatIcon} from './chat';
export {default as FAQIcon} from './faq';
export {default as PlusIcon} from './plus';
export {default as QuestionIcon} from './question';
export {default as SignInIcon} from './signin';
export {default as SignUpIcon} from './signup';
export {default as EmailIcon} from './email';
export {default as NicknameIcon} from './nickname';
export {default as PasswordIcon} from './password';